export const MessengerActionTypes = {
  GET_CONVERSATIONS_MEMBERS_REQUEST: 'GET_CONVERSATIONS_MEMBERS_REQUEST',
  GET_CONVERSATIONS_MEMBERS_SUCCESS: 'GET_CONVERSATIONS_MEMBERS_SUCCESS',

  GET_CONVERSATION_MESSAGES_REQUEST: 'GET_CONVERSATION_MESSAGES_REQUEST',
  GET_CONVERSATION_MESSAGES_SUCCESS: 'GET_CONVERSATION_MESSAGES_SUCCESS',

  POST_CONVERSATION_MESSAGE_REQUEST: 'POST_CONVERSATION_MESSAGE_REQUEST',
  POST_CONVERSATION_MESSAGE_SUCCESS: 'POST_CONVERSATION_MESSAGE_SUCCESS',
};
