export const MessengerActionTypes = {
  GET_CONVERSATIONS_REQUEST: 'GET_CONVERSATIONS_REQUEST',
  GET_CONVERSATIONS_SUCCESS: 'GET_CONVERSATIONS_SUCCESS',

  GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',

  POST_MESSAGE_REQUEST: 'POST_MESSAGE_REQUEST',
  POST_MESSAGE_SUCCESS: 'POST_MESSAGE_SUCCESS',
};
