export const MessengerActionTypes = {
  GET_CONVERSATIONS_MEMBERS_REQUEST: 'GET_CONVERSATIONS_MEMBERS_REQUEST',
  GET_CONVERSATIONS_MEMBERS_SUCCESS: 'GET_CONVERSATIONS_MEMBERS_SUCCESS',

  GET_CONVERSATION_MESSAGES_REQUEST: 'GET_CONVERSATION_MESSAGES_REQUEST',
  GET_CONVERSATION_MESSAGES_SUCCESS: 'GET_CONVERSATION_MESSAGES_SUCCESS',

  POST_CONVERSATION_MESSAGE_REQUEST: 'POST_CONVERSATION_MESSAGE_REQUEST',

  CHANGE_USER_LAST_MESSAGE: 'CHANGE_USER_LAST_MESSAGE',

  GET_CONVERSATIONS_NOT_SEEN_MESSAGES_REQUEST: 'GET_CONVERSATIONS_NOT_SEEN_MESSAGES_REQUEST',
  GET_CONVERSATIONS_NOT_SEEN_MESSAGES_SUCCESS: 'GET_CONVERSATIONS_NOT_SEEN_MESSAGES_SUCCESS',

  PUT_CONVERSATION_MESSAGES_SEEN_REQUEST: 'PUT_CONVERSATION_MESSAGES_SEEN_REQUEST',
  PUT_CONVERSATION_MESSAGES_SEEN_SUCCESS: 'PUT_CONVERSATION_MESSAGES_SEEN_SUCCESS',

  CONVERSATION_NEW_MESSAGE: 'CONVERSATION:NEW_MESSAGE',
  CONVERSATION_JOIN: 'CONVERSATION:JOIN',
};
