export const SettingsActionTypes = {
  SUCCESS: 'GLOBAL_SUCCESS',
  RESET_SUCCESS: 'GLOBAL_RESET_SUCCESS',

  FAILURE: 'GLOBAL_FAILURE',
  RESET_FAILURE: 'GLOBAL_RESET_FAILURE',

  LOADING: 'GLOBAL_LOADING',
  RESET_LOADING: 'GLOBAL_RESET_LOADING',
};
