export const AuthActionTypes = {
  SIGNIN_REQUEST: 'AUTH_SIGNIN_REQUEST',
  SIGNIN_SUCCESS: 'AUTH_SIGNIN_SUCCESS',
  SIGNIN_RESET: 'AUTH_SIGNIN_RESET',

  SIGNUP_REQUEST: 'AUTH_SIGNUP_REQUEST',

  VERIFY_REQUEST: 'AUTH_VERIFY_REQUEST',
  VERIFY_SUCCESS: 'AUTH_VERIFY_SUCCESS',
  VERIFY_FAILURE: 'AUTH_VERIFY_FAILURE',
};
