export const AuthActionTypes = {
  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_RESET: 'AUTH_LOGIN_RESET',

  REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  REGISTER_RESET: 'AUTH_REGISTER_RESET',

  VERIFY_REQUEST: 'AUTH_VERIFY_REQUEST',
  VERIFY_SUCCESS: 'AUTH_VERIFY_SUCCESS',
  VERIFY_FAILURE: 'AUTH_VERIFY_FAILURE',
};
