export const UserActionTypes = {
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',

  EDIT_USER_REQUEST: 'EDIT_USER_REQUEST',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_RESET: 'EDIT_USER_RESET',

  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_RESET: 'DELETE_USER_RESET',
};
