export const UserActionTypes = {
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',

  EDIT_USER_REQUEST: 'EDIT_USER_REQUEST',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_RESET: 'EDIT_USER_RESET',

  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_RESET: 'DELETE_USER_RESET',

  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  GET_PERMISSIONS_REQUEST: 'GET_PERMISSIONS_REQUEST',
  GET_PERMISSIONS_SUCCESS: 'GET_PERMISSIONS_SUCCESS',

  UPDATE_PERMISSIONS_REQUEST: 'UPDATE_PERMISSIONS_REQUEST',
};
